### ISSUE TITLE
Hi, any further development?

### ISSUE THREAD

**Issue by euneuber** [dawehner/jupyter-php#1]
This looks very promising, I'd like to contribute (sorry I'm not a python guy)...

**Comment by dawehner** [comment]
Hi!

If you look at the actual code, there is no python at all, its all written in PHP.
It would be interesting to try to use boris as evaluator

**Comment by dawehner** [comment]
Boris === https://github.com/d11wtq/boris

**Comment by castarco** [comment]
We alse have Psysh as an alternative: https://github.com/bobthecow/psysh (older than Boris, and more active than Boris). I think it would be more reliable.

Anyway, I have a bunch of questions related with this "issue":
- Anything new about this project? I'm considering forking it and making installable through Composer (registering it in Packagist). This change will include automatic generation of the kernel.json file.
- What benefits would add using a REPL like Boris or PsySH instead of the raw php-cli binary ?

**Comment by dawehner** [comment]
@castarco I totally believe that using psych would be the solution for a lot of the problems of the current "approach".

Just added you as collaborator to the project, so any help is really welcomed!
I also agree that making it installable via composer would be awesome!

Rock!

**Comment by castarco** [comment]
Hi @dawehner , thank you for the granted access. This weekend I'll devote some time to improve this Jupyter "kernel" :) , I'm very interested on improve scientific computation with PHP, and this kind of project is crucial to do it.

**Comment by dawehner** [comment]
Happy to see someone else thinking that PHP is not the worst invention of
the entire human history as some people do :)

**Comment by euneuber** [comment]
If I can be of any help -- I promise to do my best...

**Comment by castarco** [comment]
Hi @dawehner , I didn't advance on the coding side this weekend, but I've advanced on other fronts. I've been talking with the PsySH developers in Gitter and in the issues section:
- https://gitter.im/bobthecow/psysh
- https://github.com/bobthecow/psysh/issues/267

I've also been reading Jupyter & IPython documentation to learn more about how to integrate anything with Jupyter, but also to learn the differences between the IPython 2.0 protocol and the current Jupyter protocol.

@euneuber , If you want to start collaborating on this, I suggest you the following "lectures":
- http://andrew.gibiansky.com/blog/ipython/ipython-kernels/ (a little bit old, but interesting). Follow the links inside the post to learn more.
- https://jupyter-client.readthedocs.org/en/latest/ , this is the latest Jupyter client documentation, the one I'll follow to implement the new changes I have in mind.

My following steps will be:
- create the "TODO list" in the issues tracker, create some tags for the issues (_question_, _enhancement_, _new feature_, _bug_, _help wanted_, _QA_)
- etc (I'll use the TODO list to post the following ones!)

Cheers.
