### ISSUE TITLE
PHAR distribution

### ISSUE THREAD

**Issue by castarco** [dawehner/jupyter-php#10]
It would be nice to create a PHAR single binary to make easier the usage of PHP-Jupyter for people without knowledge on Composer or PHP.

**Comment by dawehner** [comment]
Composer is also not for installing just package management IMHO

**Comment by castarco** [comment]
@dawehner Yep, composer has much more use cases than simple package management. But in some ways it can be considered as another dependency.

The idea is not to remove Composer integration (I love Composer, and in my opinion using Composer is better than using monolithic binaries), but to create an alternative distribution of PHP-Jupyter to cover more use cases (in the same way Apple promotes static-linked and independent packages instead of promoting the usage of shared libraries as commonly done in the Unix world).

**Comment by castarco** [comment]
Solved, but in another projects:
- https://github.com/Litipk/Jupyter-PHP (new Jupyter kernel, with some improvements over this).
- https://github.com/Litipk/Jupyter-PHP-Installer (the PHAR installer)
