### ISSUE TITLE
Documentation: Please add info about ZMQ

### ISSUE THREAD

**Issue by minthemiddle** [dawehner/jupyter-php#11]
`jupyter-php` requires ZMQ and outputs a rather complicated and not easy to fix error message if you don't have it.

You may add to your documentation, that - at least for Ubuntu 14.04, you need to `sudo apt-get install libzmq-dev` and build a PHP with ZMQ support, such as in [this script](https://gist.githubusercontent.com/Kamisama666/da9ef33b1adf4c6d39ca/raw/4a04f958e90d70c69f892244abc691ab762fa697/phpzmqinstall.sh).

That's how I got it running. It may help others.

**Comment by JGrubb** [comment]
For Mac with Homebrew it's `brew install zmq`

**Comment by castarco** [comment]
Hi @minthemiddle and @JGrubb , I've started a couple of related projects:
- https://github.com/Litipk/Jupyter-PHP (new Jupyter kernel, with some improvements over this).
- https://github.com/Litipk/Jupyter-PHP-Installer (the PHAR installer)

to improve the kernel and help users installing it. There is a lot of work to do yet, but I'm working on the documentation.
