### ISSUE TITLE
Broken under Jupyter : Move from IPython 2.0 protocol to Jupyter 4.2 (protocol 5.0)

### ISSUE THREAD

**Issue by bkahlerventer** [dawehner/jupyter-php#2]
Jupyter keeps on restarting the kernel as it is not responding...

**Comment by castarco** [comment]
Related texts & documentation:
- http://andrew.gibiansky.com/blog/ipython/ipython-kernels/ (a little bit old, but interesting). Follow the links inside the post to learn more.
- https://jupyter-client.readthedocs.org/en/latest/ , this is the latest Jupyter client documentation.

**Comment by castarco** [comment]
I'm working on this issue, but also working at the same time on #6 , because the best way to use a PHP kernel is "installing" it in the Jupyter kernels directory.

**Comment by castarco** [comment]
Solved, but in other projects:
- https://github.com/Litipk/Jupyter-PHP (new Jupyter kernel, with some improvements over this).
- https://github.com/Litipk/Jupyter-PHP-Installer (the PHAR installer)
